name: Coletar resultados

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  coletar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Rodar coletor
        run: python coletor.py
